name: publish
on: [push]
jobs:
publish-hello-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: rahulvk007
password: ${{ secrets.KEY }}
- name: Build the hello-docker Docker image
run: |
       docker build . --tag ghcr.io/rahulvk007/hello-docker-gcr:latest
       docker run ghcr.io/rahulvk007/hello-docker-gcr:latest
       docker push ghcr.io/rahulvk007/hello-docker-gcr:latest